* Groundwater Simulations Using Flopy

** Introduction

[[https://github.com/modflowpy/flopy][Flopy]] is a python library which can interact with [[https://www.usgs.gov/software/modflow-6-usgs-modular-hydrologic-model][MODFLOW]] program for you. It can be used to make the models, the files and to do the postprocessing of the results from modeflow output.

In this repo there are 4 models written in python that does different things in flopy all involving some groundwater simulation scenarios, and are in increasing order of difficulties.

** Contents

- [[./docs/0_installation.org][installation]]
- [[./docs/1_github-model.org][github-model]]
- [[./docs/2_simple-model.org][simple-model]]
- [[./docs/3_water-withdrawal-controversy.org][water-withdrawal-controversy]]
- [[./docs/4_calibration.org][calibration]]

  
** Declaimer
The problem statements used in the modeling of this exercises comes from [[https://www.magnet4water.net/FeaturedProblems.aspx?CategoryId=47][magnet4water curriculum]]. Once all those problems were solved from the magnet website's cloud platform, same things was tried to achieved using flopy to compare the results as well as overall difficulties of making the models. I have no association with both and all of this was done for learning purposes.
